# Generated by Django 4.2.17 on 2024-12-17 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Murojaat nomi')),
                ('description', models.TextField(verbose_name='Murojaat tavsifi')),
                ('category', models.CharField(choices=[('network', 'Tarmoq muammosi'), ('hardware', 'Uskuna muammosi'), ('software', "Dasturiy ta'minot"), ('other', 'Boshqa')], max_length=20, verbose_name='Kategoriya')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
        ),
    ]
