# Generated by Django 4.2.17 on 2024-12-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_category_remove_ticket_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
