# Generated by Django 4.2.17 on 2024-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_updated_at_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('closed', 'Yopilgan')], default='new', max_length=20),
        ),
    ]
