# Generated by Django 4.2.17 on 2024-12-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Untitled Ticket', max_length=200),
        ),
    ]
